server:
 port: 8081
 
eureka:
 client:    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://localhost:8761/eureka/
       instance:    hostname: localhost